
package support;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MovieWSImplService", targetNamespace = "http://impl.server/", wsdlLocation = "http://127.0.0.1:9999/MovieWS?wsdl")
public class MovieWSImplService
    extends Service
{

    private final static URL MOVIEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOVIEWSIMPLSERVICE_EXCEPTION;
    private final static QName MOVIEWSIMPLSERVICE_QNAME = new QName("http://impl.server/", "MovieWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/MovieWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOVIEWSIMPLSERVICE_WSDL_LOCATION = url;
        MOVIEWSIMPLSERVICE_EXCEPTION = e;
    }

    public MovieWSImplService() {
        super(__getWsdlLocation(), MOVIEWSIMPLSERVICE_QNAME);
    }

    public MovieWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOVIEWSIMPLSERVICE_QNAME, features);
    }

    public MovieWSImplService(URL wsdlLocation) {
        super(wsdlLocation, MOVIEWSIMPLSERVICE_QNAME);
    }

    public MovieWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOVIEWSIMPLSERVICE_QNAME, features);
    }

    public MovieWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MovieWSImpl
     */
    @WebEndpoint(name = "MovieWSImplPort")
    public MovieWSImpl getMovieWSImplPort() {
        return super.getPort(new QName("http://impl.server/", "MovieWSImplPort"), MovieWSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovieWSImpl
     */
    @WebEndpoint(name = "MovieWSImplPort")
    public MovieWSImpl getMovieWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.server/", "MovieWSImplPort"), MovieWSImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOVIEWSIMPLSERVICE_EXCEPTION!= null) {
            throw MOVIEWSIMPLSERVICE_EXCEPTION;
        }
        return MOVIEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
