
package support;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MovieWSImpl", targetNamespace = "http://impl.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieWSImpl {


    /**
     * 
     * @param movieName
     * @return
     *     returns support.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovie", targetNamespace = "http://impl.server/", className = "support.GetMovie")
    @ResponseWrapper(localName = "getMovieResponse", targetNamespace = "http://impl.server/", className = "support.GetMovieResponse")
    @Action(input = "http://impl.server/MovieWSImpl/getMovieRequest", output = "http://impl.server/MovieWSImpl/getMovieResponse")
    public Movie getMovie(
        @WebParam(name = "MovieName", targetNamespace = "")
        String movieName);

    /**
     * 
     * @param searchTerm
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovies", targetNamespace = "http://impl.server/", className = "support.GetMovies")
    @ResponseWrapper(localName = "getMoviesResponse", targetNamespace = "http://impl.server/", className = "support.GetMoviesResponse")
    @Action(input = "http://impl.server/MovieWSImpl/getMoviesRequest", output = "http://impl.server/MovieWSImpl/getMoviesResponse")
    public List<String> getMovies(
        @WebParam(name = "SearchTerm", targetNamespace = "")
        String searchTerm);

}
